version: '3.1'
services:
  odoo9: #меняем название 
    image: odoo:15 #тут меняем версию одо которую докер скачает к примеру если хотим одо14 то пишем  image: odoo:14 
    depends_on:
      - db
    ports:
      - "8079:8069"   #меняем порты  1 запись это наружный порт вторая внутренний  "8080:8069"
    volumes:
      - odoo9-web-data:/var/lib/odoo       #меняем пути куда будет сохранять файлы
      - ./extra-addons9:/mnt/extra-addons  #меняем пути куда будет сохранять файлы аддонов  ./extra-addons10:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
db:
    image: postgres:13                     
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo9-web-data: #меняем имя
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass

